export default {
  USER_NOT_CREATED: 'USER_NOT_CREATED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXITS',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  INCORRECT_USERNAME: 'INCORRECT_USERNAME',
  PHONE_NUMBER_NOT_REGISTERED: 'PHONE_NUMBER_NOT_REGISTERED',
  INVALID_OTP: 'INVALID_OTP',
  INVALID_DATA: 'INVALID_DATA',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN'
};
